name: Falkor CI - Security

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Custom CLI arguments for build
        required: false
        default: --release

jobs:
  CId:
    name: Security CI Suite

    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Use CodeQL v1
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Analyse Project
        uses: github/codeql-action/analyze@v1
